###
### 로그인
POST localhost:8080/login
Content-Type: application/json

{
	"userName": "01022341111",
	"password": "0000"
}

###
POST localhost:8080/login
Content-Type: application/json

{"password":"0000","userName":"01022347292"}

### 01022347292
### Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoIiwiaXNzIjoiQVRTIiwiZXhwIjoxNjY1NDA3ODY2LCJpYXQiOjE2NjI4MTU4NjYsIm1lbWJlcklkIjoiMDEwMjIzNDcyOTIifQ.ZNvJJJTeyu5G3IvzltJNGP9x2IBueLWeiq-KKOIFSYkB8fDmBg28680T-5X3fEvQ3Uy7ek2kyV8TUlYLNSuBfg

### 01022343333
### Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoIiwiaXNzIjoiQVRTIiwiZXhwIjoxNjY1OTgwMzk0LCJpYXQiOjE2NjMzODgzOTQsIm1lbWJlcklkIjoiMDEwMjIzNDMzMzMifQ.eGIbPv_iezq5FEt9KYe2qg3J4F0Iscfri3bxO5lgPMPxmuz5xuKY-cuay3fmgfceUhLLpD_wOJN7lQE5ESCC1w

### 01022341111
### Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoIiwiaXNzIjoiQVRTIiwiZXhwIjoxNjY1OTgwNjA4LCJpYXQiOjE2NjMzODg2MDgsIm1lbWJlcklkIjoiMDEwMjIzNDExMTEifQ.Bw_OBSZOR_yxQtB7GYRvtnJixBtAGph68Ygg5qelBw0Qm3Om81tRpMedZUrD327o62zYvpfeRgGEL7sxGaV7vw


POST http://localhost:8080/api/request/save
accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoIiwiaXNzIjoiQVRTIiwiZXhwIjoxNjcxNzc4NjY0LCJpYXQiOjE2NjkxODY2NjQsIm1lbWJlcklkIjoiMDEwMjIzNDcyOTIifQ.rRjRBZeBnqyIyTntMoi-yj70qr6tKmgT9J95BBEh2NUzAKh6b2TyLttMQ9CTWEpU_EdO-BtnkMBRFJmROS4DAA
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="category"

TOGETHER
--WebAppBoundary
Content-Disposition: form-data; name="detail"

합께합싣아!!!
--WebAppBoundary
Content-Disposition: form-data; name="negotiationYn"

N
--WebAppBoundary
Content-Disposition: form-data; name="price"

2000
--WebAppBoundary
Content-Disposition: form-data; name="requestFileList"; filename="externalFile (16).jpg"

< externalFile (16).jpg
--WebAppBoundary
Content-Disposition: form-data; name="requestFileList"; filename="KakaoTalk_20190129_001153306.jpg"

< KakaoTalk_20190129_001153306.jpg
--WebAppBoundary
Content-Disposition: form-data; name="requestFileList"; filename="3050_1.jpg"

< 3050_1.jpg
--WebAppBoundary
Content-Disposition: form-data; name="sex"

FEMALE
--WebAppBoundary
Content-Disposition: form-data; name="title"

함께합시다!!
--WebAppBoundary--

###


